target(
    name='java-module1',
    dependencies=['java-modules/java-module1/src/main/java:java-module1']
)

target(
    name='java-module2',
    dependencies=['java-modules/java-module2/src/main/java:java-module2']
)

target(
    name='java-module2-app',
    dependencies=['java-modules/java-module2/src/main/java:java-module2-app']
)

target(
    name='scala-module1',
    dependencies=['scala-modules/scala-module1']
)

target(
    name='scala-module1-tests',
    dependencies=['scala-modules/scala-module1:tests']
)
