target (
    dependencies=['scala-modules/scala-module1/src/main/scala']
)

target (
    name='tests',
    dependencies=['scala-modules/scala-module1/src/test/scala']
)

target (
    name='test-resources',
    dependencies=['scala-modules/scala-module1/src/test/resources']
)